from typing import Protocol, List

class VectorStorePort(Protocol):
    def search(self, query: str, k: int = 3) -> List[str]: ...

class MemoryPort(Protocol):
    def push(self, drone_id: str, ticket_id: str) -> List[str]: ...
    def get(self, drone_id: str) -> List[str]: ...

class TicketPort(Protocol):
    def create(self, issue: str, severity: str, drone_id: str, notam_id: str = None) -> dict: ...
